version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    environment:
      - MYSQL_DATABASE=todo_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./volumes/db:/var/lib/mysql

  web:
    build: .
    container_name: flaskweb
    ports:
      - "5000:5000"
    volumes: 
        - ".:/code"
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_DATABASE=todo_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
